/* eslint-disable prettier/prettier */
export default {
    HOME: 'Home',
    DETAILS: 'Details',
    TABS: 'Tabs',
    COMINGSOON: 'Coming Soon',
    SEARCH: 'Search',
    PROFILE: 'PROFILE',
    LOGIN: 'Login',
    MAIN: 'Main',
    MOVIE_STACK:'Movies',
    MOVIES_LIST:'MOVIES_LIST',
    MOVIES_CATEGORIES:'MOVIES',
    PLAYER:'PLAYER',
    SERIES_STACK:'Series',
    SERIES:'SERIES_CATEGORIES',
    SERIES_SCREEN:'SERIES_SCREEN',
    SERIES_DETAILS:'SERIES_DETAILS',
    BOTTOM_STACK:'BOTTOM_STACK',
};
